name: auto seo

on:
  push:
    branches:
      - main  # 或者你希望触发工作流的分支

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main  # 或者你想要的分支名称

      - name: Install dependencies
        run: pip3 install -r requirements.txt

      - name: test
        run: python3 test.py